bright/bright/urls.py
from django.contrib import admin
from django.urls import path
from Bright_consulting.views import formulaire, liste_articles_blog, soumettre_avis, home, visa_etudiant, visa_travail, cours, visa_tourisme, service
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('avis/soumettre/', soumettre_avis, name='soumettre_avis'),
    
    path('admin/', admin.site.urls),
    path('', home, name = 'home'),
    path('visa_etudiant/', visa_etudiant ,name = 'visa_etudiant'),
    path('visa_travail/', visa_travail, name = 'visa_travail'),
    path('cours/', cours, name = 'cours'),
    path('visa_tourisme/', visa_tourisme, name = 'visa_tourisme'),
    path('service/', service, name = 'service'),
    path('blog/', liste_articles_blog, name = 'blog'),
    path('formulaire/', formulaire, name = 'formulaire'),
    
]


if settings.DEBUG:
    # Pour servir les fichiers médias (images téléchargées)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    # Pour servir les fichiers statiques (CSS, JS) non collectés
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

bright/Bright_consulting/models.py
from django.db import models

# Create your models here.
class Pays(models.Model):
    drapeau = models.ImageField(upload_to='images/', blank=True, null=True,verbose_name="Image du Drapeau")
    nom_pays = models.CharField(max_length=100, unique=True, verbose_name="Nom du Pays")
    continent = models.CharField(max_length=50)
    

    def __str__(self):
        return self.nom_pays

    class Meta:
        verbose_name_plural = "Pays"


class TypeVisa(models.Model):
    nom_visa = models.CharField(max_length=50, unique=True, verbose_name="Nom du Visa")
    description_courte = models.TextField()

    def __str__(self):
        return self.nom_visa

    class Meta:
        verbose_name = "Type de Visa"        

class ArticleDeBlog(models.Model):
    image = models.ImageField(upload_to='images/', blank=True, null=True,verbose_name="Image du Drapeau")
    titre = models.CharField(max_length=100, verbose_name="Titre de l'article")
    description = models.TextField()
    avis_entreprise = models.TextField()

    def __str__(self):
        return self.titre

    class Meta:
        verbose_name = "Articles de blog"
        verbose_name_plural = "Articles de blog"

class VisaParPays(models.Model):
    pays = models.ForeignKey(Pays, on_delete=models.CASCADE)
    type_visa = models.ForeignKey(TypeVisa, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.type_visa.nom_visa} pour {self.pays.nom_pays}"

    class Meta:
        # Assure qu'un type de visa n'est pas répertorié deux fois pour le même pays
        unique_together = ('pays', 'type_visa')
        verbose_name = "Visa par Pays"
        verbose_name_plural = "Visas par Pays"

class VictoireVoyageur(models.Model):
    nom_voyageur = models.CharField(max_length=100, verbose_name="Nom complet du Voyageur")
    metier = models.CharField(max_length=100, verbose_name="Métier ou Profession")
    pays_destination = models.CharField(max_length=100, verbose_name="Pays d'Arrivée (Destination)")
    photo = models.ImageField(upload_to='victoires_photos/', verbose_name="Photo du Voyageur") 

    # Lien vers le type de visa (relation "many-to-one")
    type_visa = models.ForeignKey(
        TypeVisa,
        on_delete=models.SET_NULL, # Gère la suppression du TypeVisa (ici, il devient NULL si le visa est supprimé)
        null=True, # Permet de ne pas avoir de visa associé
        blank=True, # Permet de laisser le champ vide dans le formulaire admin/front-end
        verbose_name="Type de Visa Obtenu"
    )

    def __str__(self):
        return f"Victoire de {self.nom_voyageur} pour {self.pays_destination}"

    class Meta:
        verbose_name = "Victoire de Voyageur"
        verbose_name_plural = "Victoires des Voyageurs"        


class Promotions(models.Model):
    pays = models.ForeignKey(Pays, on_delete=models.CASCADE)
    type_visa = models.ForeignKey(TypeVisa, on_delete=models.CASCADE)
    reduction = models.TextField(verbose_name="reduction")
    
    def __str__(self):
        return f"{self.type_visa.nom_visa} pour {self.pays.nom_pays}"

    class Meta:
        unique_together = ('pays', 'type_visa')
        verbose_name = "Promotion"
        verbose_name_plural = "Promotions"


class OffreEmploi(models.Model):
    visa_pays = models.ForeignKey(VisaParPays, on_delete=models.CASCADE, 
    limit_choices_to={'type_visa__nom_visa': 'Visa travail'}, 
    verbose_name="Lien Visa Travail")
    poste_disponible = models.CharField(max_length=100)
    salaire_mensuel_min = models.DecimalField(max_digits=12, decimal_places=2)
    salaire_mensuel_max = models.DecimalField(max_digits=12, decimal_places=2)
    exigences_specifiques = models.TextField(verbose_name="Exigences du Poste")

    def __str__(self):
        return f"{self.poste_disponible} chez({self.visa_pays.pays.nom_pays})"

    class Meta:
        verbose_name = "Offre d'Emploi"
        verbose_name_plural = "Offres d'Emploi"
        

    

class FiliereEtude(models.Model):
 
    nom_filiere = models.CharField(max_length=150, verbose_name="Nom de la Filière")
    domaine_etude = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.nom_filiere} "

    class Meta:
        verbose_name = "Filière d'Étude"
        verbose_name_plural = "Filières d'Étude"

    
class AvisVoyageur(models.Model):
    nom_auteur = models.CharField(max_length=100, verbose_name="Nom complet")
    email = models.EmailField(blank=True, null=True, verbose_name="Email (Non Public)")
    contenu_avis = models.TextField(verbose_name="Votre Avis/Témoignage")
    note = models.IntegerField(
        choices=[(i, str(i)) for i in range(1, 6)],
        default=5,
        verbose_name="Note (sur 5)"
    )
    date_soumission = models.DateTimeField(auto_now_add=True)
    approuve = models.BooleanField(default=False, verbose_name="Approuvé pour publication")

    def __str__(self):
        return f"Avis de {self.nom_auteur} - Note: {self.note}"

    class Meta:
        verbose_name = "Avis Voyageur"
        verbose_name_plural = "Avis des Voyageurs"
        ordering = ['-date_soumission']
    
class CoursLangue(models.Model):
    nom_cours = models.CharField(max_length=100, verbose_name="Nom du Cours")
    description_programme = models.TextField()

    def __str__(self):
        return self.nom_cours

    class Meta:
        verbose_name = "Cours de Langue"
        verbose_name_plural = "Cours de Langue"


class SectionHoraire(models.Model):
    cours = models.ForeignKey(CoursLangue, on_delete=models.CASCADE)
    nom_section = models.CharField(max_length=50, verbose_name="Nom de la Section (ex: Soir, Intensif)")
    jours_semaine = models.CharField(max_length=100, verbose_name="Jours (ex: Lun-Mer-Ven)")
    heure_debut = models.TimeField(verbose_name="Heure de Début")
    duree_heures = models.DecimalField(max_digits=4, decimal_places=2, verbose_name="Durée (heures)")
    prix_total = models.DecimalField(max_digits=10, decimal_places=2)
    date_debut = models.DateField(blank=True, null=True, verbose_name="Date de Début (optionnel)")

    def __str__(self):
        return f"{self.cours.nom_cours} - {self.nom_section}"

    class Meta:
        verbose_name = "Section et Horaire"
        verbose_name_plural = "Sections et Horaires"

bright/templates/base.html
{% load static %} 
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Bright Consulting{% endblock %}</title> 
    
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
    <link rel="shortcut icon" href="{% static 'favicons/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}">
    <link rel="manifest" href="{% static 'favicons/site.webmanifest' %}">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 

    {% block extra_css %}{% endblock %}

</head>
<body>
    
    <nav>
        <div class="header2">
            
            <a href="{% url 'home' %}">
                <img class="img" src="{% static 'images/logo2.png' %}" alt="Logo Bright Consulting">
            </a>

            <div class="menu-toggle" id="menuToggle">☰</div>

            <ul id="mainMenu">
                <li><a href="{% url 'home' %}">Accueil</a></li> 
                
                <li class="dropdown">
                    <a href="#" class="dropbtn">Nos programmes</a>
                    <div class="dropdown-content">
                        <a href="{% url 'visa_etudiant' %}">Visa Étudiant</a>
                        <a href="{% url 'visa_travail' %}">Visa Travail</a>
                        <a href="{% url 'visa_tourisme' %}">Visa Visiteur</a>
                    </div>
                </li>
                
                <li><a href="{% url 'service' %}">Services</a></li>
                <li><a href="{% url 'cours' %}">Cours de langue</a></li>
                <li><a href="#">Blog</a></li>
                
                <li class="nav-button">
                    <a href="{% url 'formulaire' %}" class="button">Prendre RDV</a>
                </li>
            </ul>
        </div>
    </nav>

    <section class="section">
        {% block content %}
        {% endblock %}
    </section>

    <div class="main-container">
        
        <header class="header-section">
            <h1>Restez informé: nos actualités et conseils</h1>
            <div class="content-wrapper">
                <div class="left-panel">
                    <p>Suivez toutes les actualités en fonction de votre engagement ici</p>
                    <a href="{% url 'blog' %}" class="blog-button">Blog</a> 
                </div>
                <div class="article-cards">
                    <div class="card">
                        <img class="card-image-placeholder" src="{% static 'images/blog1.webp' %}" alt="Pourquoi étudier en belgique?">
                        <h2>Pourquoi étudier en belgique?</h2>
                        <p class="subtitle">les nouvelles réalités</p>
                        <button class="view-more-button">Voir plus</button>
                    </div>
                    <div class="card">
                        <img class="card-image-placeholder" src="{% static 'images/blog2.webp' %}" alt="les nouvelles règles au canada en 2025">
                        <h2>les nouvelles règles au canada en 2025</h2>
                        <p class="subtitle">les nouvelles réalités</p>
                        <button class="view-more-button">Voir plus</button>
                    </div>
                </div>
            </div>
        </header>
        
        <footer class="site-footer">
            <div class="footer-section footer-left">
                <img src="{% static 'images/logo2.png' %}" alt="Bright Consulting Logo" class="logo">
                <p>Située à Douala Bonamoussadi</p>
                <p>en face de Santa Lucia</p>
                <p>Ouvert de Mardi à vendredi de 8H30 à 17h30.</p>
                <p>Le Lundi ouvert à 7H30</p>
                <p>Samedi de 8H30 à 13H00</p>
            </div>

            <div class="footer-section footer-center">
                <h3>Prêt à commencer votre aventure?<br> nous sommes disponibles</h3>
                <p class="texte">N'hésitez pas à nous contacter pour prendre rendez-vous.</p>
                <button class="rdv-button">Prendre RDV maintenant</button>
                <p class="position_text">Retrouvez nous sur :</p>
                <ul class="position">
                    <li><i class="fa-brands fa-facebook"></i></li>
                    <li><i class="fa-brands fa-tiktok"></i></li>
                    <li><i class="fa-brands fa-instagram"></i></li>
                </ul>
            </div>
            <div class="footer-section footer-right">
                <h3 class="contact1">Contactez nous au:</h3>
                <p class="phone-number">+237 676 54 72 19</p> 
                <p>ou</p>
                <button class="whatsapp-button">WhatsApp</button>
            </div>
            
            <div class="copyright-bar">
                <p>© Copyright 2022. All Rights Reserved by Bright Consulting</p>
            </div>
        </footer>
    </div>
    
    <a href="https://wa.me/237676547219" class="whatsapp-float" target="_blank">
        <i class="fa-brands fa-whatsapp"></i>
        <span class="whatsapp-text">WhatsApp</span>
    </a>
    
    <script src="{% static 'js/home.js' %}"></script>
    
    

</body>
</html>

bright/templates/blog.html
{% extends 'base.html' %}

{% load static %}


<h1>{{ titre_page }}</h1>


    {% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}"> 
    {% endblock %}

{% block content %}

    
    {% if articles %}
        <div class="articles-grid">
            {% for article in articles %}
                <div class="article-card">
                    
                    {% if article.image %}
                        <img src="{{ article.image.url }}" alt="Image de {{ article.titre }}" class="article-image">
                    {% endif %}
                    
                    <div class="article-content">
                        <h2>{{ article.titre }}</h2>
                        
                        <p class="description">{{ article.description }}</p>
                        
                        <div class="avis-section">
                            <p><strong>Note de l'entreprise :</strong> {{ article.avis_entreprise }}</p>
                        </div>
                        
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Aucun article n'a été publié pour le moment.</p>
    {% endif %}

{% endblock %}

bright/templates/cours.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/cours.css' %}">
{% endblock %}



{% block content %}

<div class="image-header-slideshow">
    <div class="slide-item one"></div>
    <div class="slide-item two"></div>
    <div class="slide-item three"></div>
</div>

<h1 class="langue">{{ titre }}</h1>

{% if tous_les_cours %}
<div class="cours-liste-container">
    {% for cours in tous_les_cours %}
    <div class="cours-card">
        <h2>{{ cours.nom_cours }}</h2>
        <p class="description">{{ cours.description_programme }}</p>

        <hr>

        <!-- <h3>Sections et Horaires Disponibles</h3> -->

        {% if cours.sectionhoraire_set.all %}
        <div class="sections-grid">
            {% for section in cours.sectionhoraire_set.all %}
            <!-- <div class="section-item">
                <h4>{{ section.nom_section }}</h4>
                <ul>
                    <li><strong>Jours :</strong> {{ section.jours_semaine }}</li>
                    <li><strong>Heure de Début :</strong> {{ section.heure_debut|time:"H:i" }}</li>
                    <li><strong>Durée :</strong> {{ section.duree_heures }} heures</li>
                    <li><strong>Prix Total :</strong> {{ section.prix_total }}</li>
                    {% if section.date_debut %}
                    <li><strong>Date de Début :</strong> {{ section.date_debut|date:"d M Y" }}</li>
                    {% endif %}
                </ul>
            </div> -->
            {% endfor %}
        </div>
        {% else %}
        <!-- <p>Aucune section ni horaire n'est actuellement programmé pour ce cours.</p> -->
        {% endif %}
    </div>
    {% endfor %}
</div>
{% else %}
<p>Aucun programme de cours de langue n'est actuellement répertorié.</p>
{% endif %}


{% endblock %}

bright/templates/formulaire.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/formulaire.css' %}">
{% endblock %}

{% block content %}
<script src="{% static 'js/formulaire.js' %}"></script>

<div class="form-container">
    <h2>🚀 Demande de Rendez-vous chez Bright Consulting</h2>

    <form>
        <div class="form-group">
            <label for="nom">Nom & Prénom(s) :</label>
            <input type="text" id="nom" name="Nom" required>
        </div>

        <div class="form-group">
            <label for="tel">Téléphone :</label>
            <input type="tel" id="tel" name="Tél" required>
        </div>

        <div class="form-group">
            <label for="email">Email :</label>
            <input type="email" id="email" name="Email">
        </div>

        <div class="form-group">
            <label for="projet">Projet d'Immigration :</label>
            <select id="projet" name="Projet" required>
                <option value="">Sélectionnez un projet</option>
                <option value="Études">Études à l'étranger (visa étudiant)</option>
                <option value="Travail">Permis de travail/Emploi (visa travail)</option>
                <option value="Regroupement">Tourisme (visa visiteur)</option>
                <option value="Autre">Autres</option>
            </select>
        </div>

        <div class="form-group">
            <label for="pays">Pays de destination :</label>
            <input type="text" id="pays" name="Pays" placeholder="Ex: Canada, France..." required>
        </div>

        <div class="form-group">
            <label for="date">Date souhaitée :</label>
            <input type="date" id="date" name="Date" required>
        </div>

        <div class="form-group">
            <label for="heure">Heure souhaitée :</label>
            <input type="time" id="heure" name="Heure" required>
        </div>

        <div class="form-group">
            <label for="nom">Motif de la demande :</label>
            <input type="text" id="motif" name="Nom" required>
        </div>

        <button class="button-envoie" type="submit">Envoyer la Demande</button>
    </form>
</div>
{% endblock %}

bright/templates/services.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/services.css' %}">
{% endblock %}


{% block content %}
<div class="image-header-slideshow">
    <div class="slide-item one"></div>
    <div class="slide-item two"></div>
    <div class="slide-item three"></div>
</div>
<div class="text">
    <h1>Nos services</h1>
</div>

<section class="services-digital-section">
    <p class="section-description">Découvrez comment nous pouvons vous aider à atteindre vos objectifs.</p>

    <div class="services-header-content">
        <h2 class="services-title">Services Informatiques & Digital</h2>
        <div class="services-image-container">
            <img src="{% static 'images/info.jpg' %}" alt="Développeur travaillant sur trois écrans"
                class="service-main-image">
        </div>
    </div>

    <div class="services-cards-container">

        <div class="service-card">
            <h3 class="card-title-pink">Branding & Identité Visuelle</h3>
            <p class="card-text">Création de supports graphiques percutants pour vos campagnes de marketing. Création de
                logos et de chartes graphiques pour une image de marque unique et mémorable.</p>
        </div>

        <div class="service-card">
            <h3 class="card-title-pink">Création de Sites Web</h3>
            <p class="card-text">Conception et développement de sites web professionnels, modernes et optimisés pour le
                référencement.</p>
        </div>

        <div class="service-card">
            <h3 class="card-title-pink">Applications Mobiles & Web</h3>
            <p class="card-text">Développement d'applications sur mesure pour iOS, Android et le web, pour répondre à
                vos besoins spécifiques.</p>
        </div>

    </div>

    <section class="services-management">
        <h3>Services de Conseil et de Gestion</h3>

        <div class="image-container">
            <img src="{% static 'images/visa.jpg' %}" alt="Développeur travaillant sur trois écrans">

        </div>

        <div class="service-card visa-service">
            <h4>Service VISA</h4>
            <p>Assistance complète pour l'obtention de visas pour diverses destinations. Nous simplifions vos démarches
                administratives.</p>
        </div>

        <div class="service-card community-management">
            <h4>Community Management</h4>
            <p>Gestion de vos réseaux sociaux pour augmenter votre visibilité, engager votre audience et construire une
                communauté fidèle.</p>
        </div>

        <div class="clear"></div>
    </section>

    <section class="services-management">
        <div class="service-category">
            <h3>Services de Logistique & E-commerce</h3>
            <div class="image-container logistic-image">
                <img src="{% static 'images/commerce.jpg' %}" alt="Développeur travaillant sur trois écrans">

            </div>

            <div class="service-card purple-bg">
                <h4>Livraison Rapide</h4>
                <p>Service de livraison fiable et sécurisé pour vos colis et documents, à l'échelle locale.</p>
            </div>

            <div class="service-card purple-bg">
                <h4>Boutique E-commerce</h4>
                <p>Création de votre boutique en ligne clé en main pour vendre vos produits et services 24/7.</p>
            </div>
            <div class="clear"></div>
        </div>
    </section>



    <section class="training-section">
        <h3>Cours de Langue & Formations</h3>

        <div class="training-image-container">


        </div>

        <div class="card-group">
            <div class="training-card language-card">
                <h4>Cours de Langue</h4>
                <p>Apprenez l'anglais, l'allemand et l'italien avec nos cours interactifs pour tous les niveaux.</p>
            </div>

            <div class="training-card professional-card">
                <h4>Formations Professionnelles</h4>
                <p>Développez vos compétences avec nos formations en</p>
                <p>Graphic Design, Web Design, Montage Vidéo et Création d'Applications.</p>
            </div>
        </div>

        <div class="clear"></div>
    </section>
</section>


{% endblock %}

bright/templates/visa_travail.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/visa_travail.css' %}">
{% endblock %}

{% block content %}

<script src="{% static 'js/travail.js' %}"></script>

<section>


    <div class="image-header-slideshow">
        <div class="slide-item one"></div>
        <div class="slide-item two"></div>
        <div class="slide-item three"></div>
    </div>
    <div class="text">
        <h1>Souhaitez-vous travailler à l'étranger?? Nous sommes là pour <br><span class="text2"> vous accompagner dans
                votre procédure</span></h1>
    </div>

    <div class="container my-5">
        <h1 class="text-center mb-4">{{ titre_page }}</h1>

        <div class="intro-message-box">
            <p>
                Veuillez dérouler les cartes Pays ci-dessous pour voir les différentes offres de poste disponibles pour
                le Visa Travail.
            </p>
        </div>

        <div class="filter-controls mb-4">
            <input type="text" id="global-search" placeholder="Rechercher un pays ou un poste..." class="search-input">
        </div>

        <p id="no-results-message" class="alert-message text-center" style="display: none;">Désolé, ce pays ou ce poste
            n'existe pas.</p>

        {% if offres_regroupees %}
        <div id="accordion-visa-travail">
            {% for pays, offres_liste in offres_regroupees %}
            <div class="country-card" data-country-name="{{ pays.nom_pays }}">

                <div class="country-header" data-country-id="{{ pays.id }}">
                    {% if pays.drapeau %}
                    <img src="{{ pays.drapeau.url }}" alt="Drapeau de {{ pays.nom_pays }}" class="country-flag">
                    {% endif %}
                    <h2>{{ pays.nom_pays }} ({{ offres_liste|length }} Offre{{ offres_liste|length|pluralize }})</h2>
                    <span class="toggle-icon">+</span>
                </div>

                <div class="offers-content" id="content-{{ pays.id }}">

                    <div class="offers-grid">
                        {% for offre in offres_liste %}
                        <div class="job-offer-card" data-job-title="{{ offre.poste_disponible|lower }}">
                            <h3>{{ offre.poste_disponible }}</h3>


                            <div class="job-details">
                                <p>
                                    <i class="fas fa-money-bill-wave"></i> Salaire Mensuel: {{ offre.salaire_mensuel_min }} - {{ offre.salaire_mensuel_max }} euro
                                </p>
                                <div class="requirements-box">
                                    <h4>Exigences du Poste:</h4>
                                    <p>{{ offre.exigences_specifiques|linebreaksbr }}</p>
                                </div>

                            </div>
                        </div>
                        {% endfor %}
                    </div>

                </div>
            </div>

            {% endfor %}
        </div>
        {% else %}
        <p class="text-center alert-info">Aucune offre d'emploi de type "Visa Travail" n'est disponible pour le moment.
        </p>
        {% endif %}
    </div>

    <!-- documentation -->
    <h2 class="titre">Documents nécessaires pour débuter votre procédure</h2>
    <div class="document-container">

        <ul>
            <li>Scan passeport</li>
            <li>Demi photo numérique 4x4</li>
            <li>CV</li>
            <li>Certificat médical</li>
            <li>Dernières attestation de travail </li>
            <li>Extrait de casier judiciaire</li>

        </ul>
    </div>

    <!-- victoires -->
<!-- 
    <p class="vict">Ils sont nombreux à avoir réuissit leurs procédures sans aucunes intérruption faites nous confiance
        et lancez <br>
        <span class="vict2">votre procédure vous ne serez pas décu</span>
    </p>

    <h1>{{ titre_page2 }}</h1>

    {% if victoires %}
    <div class="liste-victoires">
        {% for victoire in victoires %}
        <div class="carte-victoire">
            <img src="{{ victoire.photo.url }}" alt="Photo de {{ victoire.nom_voyageur }}">
            <h2>{{ victoire.nom_voyageur }}</h2>
            <p>
                <strong>Métier :</strong> {{ victoire.metier }}<br>
                <strong>Destination :</strong> {{ victoire.pays_destination }}
            </p>
            {% if victoire.type_visa %}
            <p class="visa-type">
                Visa obtenu : {{ victoire.type_visa.nom_visa }}
            </p>
            {% endif %}
        </div>
        <hr>
        {% endfor %}
    </div>
    {% else %}
    <p>Aucune victoire enregistrée pour le Visa de Travail pour le moment.</p>
    {% endif %} -->

    <!-- contacts -->
    <p class="vict">qu’attendez-vous pour lancer votre procédure?? nous sommes disponible 24h/24. N’hésitez pas à
        <br>nous contacter ou nous appeler
    </p>

    <div class="contact-buttons-container">
        <a href="https://wa.me/237676547219" class="contact-button whatsapp-button" target="_blank">
            <i class="fab fa-whatsapp"></i> WhatsApp
        </a>
        <a href="tel:+237655667744" class="contact-button call-button">
            <i class="fas fa-phone"></i> +237 676 54 72 19
        </a>
    </div>
</section>

<!-- FAQ -->
<h1>{{titre_page3}}</h1>

<div class="faq-container">

    <div class="faq-item">
        <button class="faq-question" aria-expanded="false">
            Quels sont les critères pour obtenir un visa de travail ?
            <span class="faq-icon">+</span>
        </button>
        <div class="faq-answer-container">
            <p class="faq-answer">
                Les critères varient selon le pays, mais ils incluent généralement : une offre d’emploi valide, des
                compétences adaptées au poste, un passeport en cours de validité et parfois une preuve d’expérience
                professionnelle. Nous vous aidons à vérifier votre éligibilité selon la destination choisie.
            </p>
        </div>
    </div>

    <div class="faq-item">
        <button class="faq-question" aria-expanded="false">
            Ai-je besoin d’une promesse d’embauche avant de demander un visa travail ?
            <span class="faq-icon">+</span>
        </button>
        <div class="faq-answer-container">
            <p class="faq-answer">
                Dans la majorité des pays, oui. Il est obligatoire d’avoir une offre d’emploi officielle pour lancer la
                procédure. Certaines destinations proposent aussi des programmes ouverts permettant une recherche
                d’emploi sur place. Nous vous guidons selon votre profil.
            </p>
        </div>
    </div>

    <div class="faq-item">
        <button class="faq-question" aria-expanded="false">
            Combien de temps prend l’obtention d’un visa travail ?
            <span class="faq-icon">+</span>
        </button>
        <div class="faq-answer-container">
            <p class="faq-answer">
                Les délais varient de 4 à 16 semaines selon le pays et la nature du contrat de travail. Bright
                Consulting effectue un suivi constant afin de vous informer dès qu’une mise à jour est disponible.
            </p>
        </div>
    </div>

    <div class="faq-item">
        <button class="faq-question" aria-expanded="false">
            Le visa travail peut-il mener à la résidence permanente ?
            <span class="faq-icon">+</span>
        </button>
        <div class="faq-answer-container">
            <p class="faq-answer">

                Dans certains pays comme le Canada, l’Allemagne ou l’Australie, un visa travail peut servir de
                passerelle vers la résidence permanente. Nous vous conseillons sur les options possibles en fonction de
                vos ambitions professionnelles.
            </p>
        </div>
    </div>

</div>

<section class="avis-section">
    <h2>Laissez-nous votre Témoignage</h2>

    <form method="post" action="{% url 'soumettre_avis' %}">
        {% csrf_token %}

        {% include 'avis/formulaire_avis.html' with form=form_avis %}

        <button type="submit" class="btn btn-primary">Soumettre mon Avis</button>
    </form>

</section>






{% endblock %}